<?php

namespace Tests\Unit;

use CommsExpress\CDN\File;

class FileTest extends \PHPUnit\Framework\TestCase
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->file = new \CommsExpress\CDN\File();
    }

    /** @test */

    public function it_can_be_instantiated()
    {
        $this->assertInstanceOf(File::class, $this->file);
    }

    /** @test */

    public function it_has_an_id()
    {
        $this->file->setID(1);
        $this->assertEquals(1, $this->file->getID());
    }

    /** @test */

    public function it_has_a_url()
    {
        $this->file->setURL('http://cdn.test');
        $this->assertEquals('http://cdn.test', $this->file->getURL());
    }
}